spring:
  datasource:
    url: jdbc:mysql://localhost:3306/world?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL57Dialect
    show-sql: false
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
server:
  error:
    whitelabel:
      enabled: false
    path: /error